swagger: "2.0"
info:
  description: Swagger file
  version: "1.0.0"
  title: Swagger ReST Usuarios
consumes:
  - application/json
produces:
  - application/json

basePath: /api

paths:
  /usuariosprofe:
    get:
      x-swagger-router-controller: Resources
      operationId: usuariosProfessor.read_all
      tags:
        - Usuarios Professor - Read All - GET
      summary: Lista de Usuarios
      description: Lista de Usuarios
      responses:
        200:
          description: Sucesso na leitura de Usuarios
          schema:
            type: array
            items:
              properties:
                fname:
                  type: string
                lname:
                  type: string
                timestamp:
                  type: string
    post:
      x-swagger-router-controller: Resources
      operationId: usuariosProfessor.create
      tags:
        - Clientes Novo Swagger
      summary: Cria uma pessoa e adiciona na lista de Clientes
      description: Adiciona na lista de Clientes
      parameters:
        - name: person
          in: body
          description: Pessoa a ser criada
          required: True
          schema:
            type: object
            properties:
              fname:
                type: string
                description: Primeiro nome
              lname:
                type: string
                description: Ultimo nome
      responses:
        201:
          description: Sucesso ao criar

  /usuariosprofe/{lname}:
    get:
      x-swagger-router-controller: Resources
      operationId: usuariosProfessor.read_one
      tags:
        - Usuarios Professor -  More Methods -  GET POST PUT DELETE
      summary: Leitura de uma pessoa da lista de Clientes
      description: Leitura de uma pessoa
      parameters:
        - name: lname
          in: path
          description: Ultimo nome
          type: string
          required: True
      responses:
        200:
          description: Sucesso na leitura de uma pessoa
          schema:
            properties:
              fname:
                type: string
              lname:
                type: string
              timestamp:
                type: string
    put:
      x-swagger-router-controller: Resources
      operationId: usuariosProfessor.update
      tags:
        - Clientes Novo Swagger
      summary: Update na lista de Clientes
      description: Update na lista
      parameters:
        - name: lname
          in: path
          description: Ultimo nome
          type: string
          required: True
        - name: person
          in: body
          schema:
            type: object
            properties:
              fname:
                type: string
              lname:
                type: string
      responses:
        200:
          description: Sucesso ao atualizar
    delete:
      x-swagger-router-controller: Resources
      operationId: usuariosProfessor.delete
      tags:
        - Clientes Novo Swagger
      summary: Deletar uma pessoa na lista de Clientes
      description: Deleta uma pessoa
      parameters:
        - name: lname
          in: path
          type: string
          required: True
      responses:
        200:
          description: Sucesso ao deletar
  /usuarios:
    get:
      x-swagger-router-controller: Resources
      operationId: usuarioList.get
      tags:
        - MEU MONGO - USUARIOS GET ALL
      summary: Lista de Usuarios
      description: Lista de Usuarios
      responses:
        200:
          description: Sucesso na leitura de Usuarios
          schema:
            type: array
            items:
              properties:
                _id:
                  type: string
                sobrenome:
                  type: string
                address:
                  type: string
                celular:
                  type: string
                tipo_usuario:
                  type: string
  /items:
    get:
      x-swagger-router-controller: Resources
      operationId: itemList.get
      tags:
        - MEU MONGO - ITEMS GET ALL
      summary: Lista de ITEMS
      description: Lista de Items
      responses:
        200:
          description: Sucesso na leitura de Items
          schema:
            type: array
            items:
              properties:
                _id:
                  type: string
                nome:
                  type: string
                descricao:
                  type: string
                data_inicio:
                  type: string
                data_final:
                  type: string
                status:
                  type: string
